// src/components/AppGrid.jsx
import React, { useState, useEffect, useCallback } from 'react';
import { useWindows } from '@/store/WindowsContext';
import { getIconPath } from '@/utils/imagePath';
import fileIconImg from '@/assets/FileWindow/file.png';
import './AppGrid.css';

export default function AppGrid() {
  const windowsStore = useWindows();
  const [gridHeight, setGridHeight] = useState('');

  useEffect(() => {
    const h = windowsStore.getFullscreenWindowHeight();
    const numericH = parseInt(h, 10);
    setGridHeight(numericH - 60 + 'px');
  }, [windowsStore]);

  const openWindow = useCallback(
    (windowId) => {
      windowsStore.setWindowState({ windowState: 'open', windowId });
    },
    [windowsStore]
  );

  const openHelloHand = useCallback(() => {
    window.open('//hellohand.bobrek.dev');
  }, []);

  return (
    <nav className="grid-container" style={{ height: gridHeight }}>
      <li>
        <button
          className="icon"
          onTouchStart={openHelloHand}
          onDoubleClick={openHelloHand}
        >
          <img className="ag-icon-image" src={fileIconImg} alt="hellohand" />
          <div className="ag-border-box">
            <p className="ag-icon-text">HelloHand</p>
          </div>
        </button>
      </li>
      {windowsStore.windows
        .filter((w) => w.showInAppGrid !== false)
        .map((win) => (
          <li key={win.windowId}>
            <button
              className="icon"
              onTouchStart={() => openWindow(win.windowId)}
              onDoubleClick={() => openWindow(win.windowId)}
            >
              <img
                className="ag-icon-image"
                src={getIconPath(win.iconImage)}
                alt={win.altText}
              />
              <div className="ag-border-box">
                <p className="ag-icon-text">{win.displayName}</p>
              </div>
            </button>
          </li>
        ))}
    </nav>
  );
}

// templates/AppGrid.vue
<script setup>
import {useWindowsStore} from '@/stores/windows'
import { onMounted } from 'vue';

const windowsStore = useWindowsStore()

const gridHeight = ref("")

const openWindow = (windowId) => {
    const payload = {
        windowState: "open",
        windowId: windowId
    }
    windowsStore.setWindowState(payload)
}

const openHelloHand = () => {
    window.open("//hellohand.bobrek.dev");
}


const getImagePath = (iconImage) => {
    const path = `../assets/win95Icons/${iconImage}`;
    const modules = import.meta.glob("../assets/win95Icons/*", { eager: true });
    const mod = modules[path]
    return mod.default;
};

onMounted(() => {
    let gridH = windowsStore.getFullscreenWindowHeight
    gridHeight.value = gridH.substring(0, gridH.length - 2) - 60 + "px"
})
</script>

<template>
    <nav class="grid-container" :style="{ height: gridHeight }">
    <li>
      <button
        class="icon"
        @touchstart="openHelloHand()"
        @dblclick="openHelloHand()"
      >
      <img class="icon-image" src="@/assets/FileWindow/file.png" alt="hellohand" />
        <div class="border-box">
          <p class="icon-text">
            HelloHand
          </p>
        </div>
      </button>
    </li>
    <li v-for="window in windowsStore.windows" :key="window.key">
      <button
        class="icon"
        v-if="window.showInAppGrid != false"
        @touchstart="openWindow(window.windowId)"
        @dblclick="openWindow(window.windowId)"
      >
      <img class="icon-image" :src=getImagePath(window.iconImage) :alt="window.altText" />
        <div class="border-box">
          <p class="icon-text">
            {{ window.displayName }}
          </p>
        </div>
      </button>
    </li>
  </nav>
</template>
