// app.vue
<script setup>
import FileWindow from './templates/FileWindow.vue'
import Window from './templates/Window.vue'
import Navbar from './templates/Navbar.vue'
import AppGrid from './templates/AppGrid.vue'
import Bio from './views/Bio.vue'
import Resume from './views/Resume.vue'
import ImagePreviewWindow from './templates/ImagePreviewWindow.vue'
import StartMenu from './templates/StartMenu.vue'
import {
    useWindowsStore
} from './stores/windows'
const windowsStore = useWindowsStore()
const windows = windowsStore.windows

const windowComponents = [
  { name: 'window', comp: Window },
  { name: 'ImagePreviewWindow', comp: ImagePreviewWindow },
  { name: 'FilesWindow', comp: FileWindow }
]

const slotViews = [
  { name: 'bio', comp: Bio },
  { name: 'resume', comp: Resume },
]

const windowCheck = (windowId) => {
    if (windowsStore.getWindowById(windowId).windowState == "open") {
        return true
    } 
}

const deinitWindows = () => {
  if (windowsStore.activeWindow == "Menu") {
    windowsStore.setActiveWindow("")
    windowsStore.zIndexIncrement("")
  }
}

const openWindow = (windowId) => {
  const payload = {
    windowState: "open",
    windowId: windowId
  }
  windowsStore.setWindowState(payload)
}

onMounted(() => {
  let navbar = document.getElementById("navbar");
  let navbarHeight = navbar.clientHeight;

  document.getElementById("screen").style.height =
  window.innerHeight - navbarHeight + "px";

  window.addEventListener("resize", () => {
    let vh = window.innerHeight * 0.01;
    document.documentElement.style.setProperty("--vh", `${vh}px`);
  });
  // openWindow('BiographyWindow')
})

</script>

<template>
  <div id="app">
    <div class="screen" id="screen" @click="deinitWindows">
      <div 
        v-for="window in windows" 
        :key="window.key" 
        :aria-label="window.displayName"
      >
          <component 
            :is="windowComponents.find(comp => comp.name === window.windowComponent).comp"
            :nameOfWindow="window.windowId" 
            :id="window.windowId" 
            :style="{
                    position: window.position,
                    left: window.positionX,
                    top: window.positionY,
                  }" 
            :folderContent="window.folderContent" 
            :folderSize="window.folderSize" 
            v-if="windowCheck(window.windowId)" 
          >
          <template v-slot:content>
            <component :is="slotViews.find(comp => comp.name === window.windowContent).comp"></component>
          </template>
          </component>
        </div>
        <AppGrid />
    </div>
    <StartMenu
      v-if="windowsStore.activeWindow == 'Menu'"
      style="position: absolute; z-index: 9999; left: 0; bottom: 36px"
    ></StartMenu>
    <navbar style="position: absolute; bottom: 0; z-index: 9999" id="navbar" />
  </div>
</template>

<style>

@import "./assets/css/utils/normalize.css";
@import "./assets/css/windows/app.css";
@import "./assets/css/windows/window.css";
@import "./assets/css/windows/appgrid.css";

@font-face {
  font-family: "MS Sans Serif";
  src: url("@/assets/fonts/MS-Sans-Serif.ttf");
}

/*-------------------------------------------*\
    Utilities
\*-------------------------------------------*/

html {
  overflow: hidden;
}

h6 {
    margin-top: 5px !important;
}

#app {
  font-family: "MS Sans Serif";
  font-weight: 400;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  display: flex;
  width: 100%;
  height: calc(var(--vh, 1vh) * 100);
  flex-direction: column;
}

.screen {
  width: 100%;
  position: relative;
  z-index: 999;
}

::-webkit-scrollbar {
  width: 15px;
  background: repeating-conic-gradient(
      rgb(189, 190, 189) 0% 25%,
      rgb(255, 255, 255) 0% 50%
    )
    50% / 2px 2px;
}
::-webkit-scrollbar-thumb {
  background: rgb(189, 190, 189);
  /* box-shadow: 1.5px 1.5px black; */
  border-top: solid rgb(250, 250, 250) 1.5px;
  border-left: solid rgb(250, 250, 250) 1.5px;
  border-bottom: solid rgb(90, 90, 90) 1.5px;
  border-right: solid rgb(90, 90, 90) 1.5px;
  outline: rgb(219, 219, 219);
}

/*-------------------------------------------*\
    Fullscreen
\*-------------------------------------------*/

.fullscreen {
  left: 0 !important;
  position: relative;
  display: block;
  top: 0 !important;
  right: 0 !important;
}
</style>

// src/App.jsx
import React, { useEffect, useCallback } from 'react';
import { useWindows } from '@/store/WindowsContext';
import Window from '@/components/Window';
import FileWindow from '@/components/FileWindow';
import ImagePreviewWindow from '@/components/ImagePreviewWindow';
import Navbar from '@/components/Navbar';
import AppGrid from '@/components/AppGrid';
import StartMenu from '@/components/StartMenu';
import Bio from '@/views/Bio';
import Resume from '@/views/Resume';

const WINDOW_COMPONENTS = {
  window: Window,
  ImagePreviewWindow: ImagePreviewWindow,
  FilesWindow: FileWindow,
};

const SLOT_VIEWS = {
  bio: Bio,
  resume: Resume,
};

export default function App() {
  const windowsStore = useWindows();

  useEffect(() => {
    const navbar = document.getElementById('navbar');
    if (navbar) {
      const navbarHeight = navbar.clientHeight;
      const screen = document.getElementById('screen');
      if (screen) {
        screen.style.height = window.innerHeight - navbarHeight + 'px';
      }
    }

    const handleResize = () => {
      const vh = window.innerHeight * 0.01;
      document.documentElement.style.setProperty('--vh', `${vh}px`);
    };
    window.addEventListener('resize', handleResize);
    handleResize();

    return () => window.removeEventListener('resize', handleResize);
  }, []);

  const deinitWindows = useCallback(() => {
    if (windowsStore.activeWindow === 'Menu') {
      windowsStore.setActiveWindow('');
      windowsStore.zIndexIncrement('');
    }
  }, [windowsStore]);

  return (
    <div id="app">
      <div className="screen" id="screen" onClick={deinitWindows}>
        {windowsStore.windows.map((win) => {
          if (win.windowState !== 'open') return null;

          const WindowComp = WINDOW_COMPONENTS[win.windowComponent];
          if (!WindowComp) return null;

          const windowStyle = {
            position: win.position,
            left: win.positionX,
            top: win.positionY,
          };

          const ContentComp = win.windowContent ? SLOT_VIEWS[win.windowContent] : null;

          return (
            <div key={win.windowId} aria-label={win.displayName}>
              <WindowComp
                nameOfWindow={win.windowId}
                style={windowStyle}
                folderContent={win.folderContent}
                folderSize={win.folderSize}
              >
                {ContentComp && <ContentComp />}
              </WindowComp>
            </div>
          );
        })}
        <AppGrid />
      </div>
      {windowsStore.activeWindow === 'Menu' && (
        <div style={{ position: 'absolute', zIndex: 9999, left: 0, bottom: '36px' }}>
          <StartMenu />
        </div>
      )}
      <Navbar />
    </div>
  );
}
